local intelephense = {
  codeAction = {
    enable = true,
    disable = { "extracConstant" },
  },
  compatibility = {
    correctForBaseClassStaticUnionTypes = true,
    correctForArrayAccessArrayAndTraversableArrayUnionTypes = true,
  },
  files = {
    maxSize = 9000000,
    associations = {
      "*.php",
      "*.phtml",
    },
    exclude = {
      "**/.git/**",
      "**/.svn/**",
      "**/.hg/**",
      "**/CVS/**",
      "**/.DS_Store/**",
      "**/node_modules/**",
      "**/bower_components/**",
      "**/vendor/**/{Tests,tests}/**",
      "**/.history/**",
      "**/vendor/**/vendor/**",
      "**/_ide_helper.php",
      "**/_ide_helper_models.php",
    },
  },
  stubs = {
    "apache",
    "bcmath",
    "bz2",
    "calendar",
    "com_dotnet",
    "Core",
    "ctype",
    "curl",
    "date",
    "dba",
    "dom",
    "enchant",
    "exif",
    "FFI",
    "fileinfo",
    "filter",
    "fpm",
    "ftp",
    "gd",
    "gettext",
    "gmp",
    "hash",
    "iconv",
    "imap",
    "intl",
    "json",
    "ldap",
    "libxml",
    "mbstring",
    "meta",
    "mysqli",
    "oci8",
    "odbc",
    "openssl",
    "pcntl",
    "pcre",
    "PDO",
    "pdo_ibm",
    "pdo_mysql",
    "pdo_pgsql",
    "pdo_sqlite",
    "pgsql",
    "Phar",
    "posix",
    "pspell",
    "readline",
    "Reflection",
    "session",
    "shmop",
    "SimpleXML",
    "snmp",
    "soap",
    "sockets",
    "sodium",
    "SPL",
    "sqlite3",
    "standard",
    "superglobals",
    "sysvmsg",
    "sysvsem",
    "sysvshm",
    "tidy",
    "tokenizer",
    "xml",
    "xmlreader",
    "xmlrpc",
    "xmlwriter",
    "xsl",
    "Zend OPcache",
    "zip",
    "zlib",
  },
  completion = {
    insertUseDeclaration = true,
    fullyQualifyGlobalConstantsAndFunctions = false,
    triggerParameterHints = true,
    maxItems = 100,
  },
  format = {
    enable = false,
    braces = "psr12",
  },
  environment = {
    documentRoot = "",
    includePaths = {},
    phpVersion = "8.2.0",
    shortOpenTag = true,
  },
  diagnostics = {
    enable = true,
    run = "onType",
    embeddedLanguages = true,
    undefinedSymbols = true,
    undefinedVariables = false,
  },
}

return intelephense
